spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: NaZaR2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

coinmarketcap:
  api:
    key: 75280beb-060d-4285-83b9-9bfb6d0d94b5
    url: https://pro-api.coinmarketcap.com/

coingecko:
  api:
    key: CG-9ymgeh5BQsnSuBx9rmiFVk7q
    url: https://api.coingecko.com/api/v3/