spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Make sure to use the correct dialect for your MySQL version
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_API_CLIENT_ID}
            client-secret: ${GOOGLE_API_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_API_REDIRECT_URI}
            scope:
              - email
              - profile

coingecko:
  api:
    key: ${COINGECKO_KEY}
    url: https://api.coingecko.com/api/v3/

google:
  api:
    clientId: ${GOOGLE_API_CLIENT_ID}
server:
  port: 8080
