spring:
  datasource:
    url: jdbc:mysql://cryptodash.mysql.database.azure.com:3306/cryptodash?useSSL=true&requireSSL=false&serverTimezone=UTC
    username: nazar
    password: V3jaL9ia
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Make sure to use the correct dialect for your MySQL version
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 696132791550-ral8gkn00orccirt8g5ar2mp66ul4ovk.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/api/v1/auth/google
            scope:
              - email
              - profile

coinmarketcap:
  api:
    key: 75280beb-060d-4285-83b9-9bfb6d0d94b5
    url: https://pro-api.coinmarketcap.com/

coingecko:
  api:
    key: CG-9ymgeh5BQsnSuBx9rmiFVk7q
    url: https://api.coingecko.com/api/v3/

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          cors: DEBUG
server:
  port: ${SERVER_PORT:80}
