name: Deploy Spring Boot Application to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' # AdoptOpenJDK перешёл на Eclipse Temurin

      - name: Grant execute permission for gradlew
        run: chmod +x ./back_end/gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar -x test
        working-directory: back_end

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cryptodashs' # Замените на имя вашего Azure Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Замените на ваш Azure publish profile secret
          package: 'back_end/build/libs/*.jar' # Путь к собранному JAR-файлу
